stages:
  - build
  - deploy dev
  - test dev
  - deploy prod
  - test prod

before_script:
  - export PATH=$PATH:/usr/local/go/bin

build:
  stage: build
  script: make build
  artifacts:
    paths:
      - server

deploy dev:
  variables:
    DEPLOY_HOST: $DEPLOY_HOST_DEV
  stage: deploy dev
  script:
    - make deploy-setup
    - make deploy-dev
