stages:
  - build
  - deploy dev
  - test dev
  - deploy prod
  - test prod

before_script:
  - export PATH=$PATH:/usr/local/go/bin

build:
  stage: build
  script: make build
  artifacts:
    paths:
      - server

deploy dev:
  variables:
    DEPLOY_HOST: $DEPLOY_HOST_DEV
  stage: deploy dev
  script:
    - make deploy-setup
    - make deploy
  environment:
    name: dev
    url: http://$DEPLOY_HOST_DEV
    on_stop: stop dev

stop dev:
  variables:
    DEPLOY_HOST: $DEPLOY_HOST_DEV
  stage: deploy dev
  script:
    - make deploy-setup
    - make stop
  environment:
    name: dev
    action: stop

test dev:
  stage: test dev
  script:
    - curl $DEPLOY_HOST_DEV

deploy prod:
  variables:
    DEPLOY_HOST: $DEPLOY_HOST_PROD
  stage: deploy prod
  script:
    - make deploy-setup
    - make deploy
  only:
    - master
  environment:
    name: prod
    url: http://$DEPLOY_HOST_PROD

test prod:
  stage: test prod
  script:
    - curl $DEPLOY_HOST_PROD
  only:
    - master
