- name: create service config
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ item.name }}.service
    owner: root
    group: root
    mode: 0644
  loop: '{{ custom_systemd_services }}'
- name: start service
  service:
    name: '{{ item.name }}'
    state: started
  loop: '{{ custom_systemd_services }}'
