---
- name: Create Systemd Service
  hosts: all
  vars:
    custom_systemd_services:
      - name: helloworld
        description: Simple Go server
        exec_start: /var/lib/apps/server
  roles:
    - custom_systemd_service
    - deploy
